baseURL = 'https://jerosanchez.github.io/blog/'
languageCode = 'en-us'
title = "Jero Sanchez"
copyright = "© Jero Sanchez"
theme = 'archie'

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A journey towards backend engineering"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jerosanchez"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/jerosanchez"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2
